#Configuracion de la aplicacion
#Tue Jun 09 10:42:59 ART 2026
alelo.1=
alelo.3=
combo.1=0
combo.2=5
combo.3=1
combo.4=7
endRFU=150
mediaNNFam=-3.14
mediaNNHEX=-2.45
mediaNPFam=1.20
mediaNPHEX=0.51
mediaPPFam=5.60
mediaPPHEX=4.91
modo.marcadores=1
primerciclo=10
promedioSuperior=5
sdNNFam=0.31
sdNNHEX=0.51
sdNPFam=0.72
sdNPHEX=0.45
sdPPFam=0.13
sdPPHEX=0.46
segundociclo=20
umbral=9000
